name: Deploy Gradio App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Export Gradio app to static HTML
      run: |
        python -m pip install gradio
        python -c "import app.ui as ui; ui.demo.launch(share=False, inline=True, inbrowser=False, prevent_thread_lock=True)"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # or wherever your static HTML lands
